version: '2.3'

services:
  r2base:
    image: registry.cn-hangzhou.aliyuncs.com/soco-images/r2base:latest
    container_name: r2base
    ports:
      - 8000:8000
    environment:
      - ES_URL = elastic:9200
    networks:
      - soco
    volumes:
    - data:/app/resources

  elastic:
    image: registry.cn-hangzhou.aliyuncs.com/soco-images/model-as-service:es-7.10.1
    container_name: elastic
    ports:
      - 9200:9200
      - 9300:9300
    env_file:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - r2base

  kibana:
    image: registry.cn-hangzhou.aliyuncs.com/soco-images/model-as-service:kibana-7.10.1
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - r2base

volumes:
  data:
    driver: local

networks:
  soco: