IS_DEBUG: false
INDEX_DIR: "_index"
MODEL_DIR: "resources"
API_PREFIX: "/r2base"
IV_BACKEND: "es"
ANN_BACKEND: "es"
ES_URL : 'http://192.1.2.219:9200'
ES_SHARD_NUM: 3
ES_REPLICA_NUM: 1
UMAP_BACKEND: cpu